Improve clang-format version parsing
BlueBrain/hpc-coding-conventions pull request #87
Opened 2021-01-16 18:04 UTC by pramodk

- On newer ubunut, clang-format print version with platform
    name at the begining : Ubuntu clang-format version 11.0.0-2~ubuntu20.04.1
  - Add clang-format binary names for v10 and v11

fixes #86

2021-01-17 08:21 UTC, alkino requested changes

2021-01-17 08:21 UTC, alkino commented on cpp/cmake/FindClangFormat.cmake
> +                     clang-format-8
You mean clang-format-9

2021-01-17 08:56 UTC, pramodk commented on cpp/cmake/FindClangFormat.cmake
> +                     clang-format-8
oh yes, thanks!

2021-01-17 10:09 UTC, alkino approved these changes

2021-01-18 08:06 UTC, tristan0x approved these changes

2021-01-18 11:21 UTC, merged